### ISSUE TITLE
desync basemap

### ISSUE THREAD

**Issue by astomas** [Igor-Vladyka/leaflet.browser.print#10]
Hi
when using the plugin my basemaps are desync: tiles around print area aren't refreshed and zoom is impossible (no console error). A workaround is to manually select another basemap after printing but I don't know how to code that in my page.
I've attached my map and code.
Greetings
[bug_print_fdc_google.zip](https://github.com/Igor-Vladyka/leaflet.browser.print/files/1429936/bug_print_fdc_google.zip)

**Comment by Igor-Vladyka** [comment]
Hi

Thanks for reporting this issue. Problem solved in current version v0.3.9, please check it out and write me it something is still not working as expected.

Regards,
Igor

**Comment by astomas** [comment]
It's all good now. Thx for support.
