### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by ynakatake** [Igor-Vladyka/leaflet.browser.print#100]
Hi.

There seems to be a memory leak in _completePrinting.
Tentatively, I was able to work around this by executing "self._map.fire(L.Control.BrowserPrint.Event.PrintEnd, ...);" followed by overlayMap.remove();.

**Comment by Igor-Vladyka** [comment]
Hello.

It may be. I plan to improve plugin and refactor it a bit soon, so will include this into next release. Thanks.

**Comment by Igor-Vladyka** [comment]
Fix integrated into the plugin in latest version.
