### ISSUE TITLE
this error pop up in chrome , how can I fix it ?

### ISSUE THREAD

**Issue by manelalayet19** [Igor-Vladyka/leaflet.browser.print#106]
leaflet.browser.print.min.js:9 Uncaught TypeError: t.getPane is not a function
    at i.onAdd (leaflet.browser.print.min.js:9)
    at i.addTo (Control.js:70)
    at test.html:55

**Comment by Igor-Vladyka** [comment]
You may be missing some part of leaflet library that this plugin is based on.

**Comment by simonschamp** [comment]
Uncaught TypeError: t.getPane is not a function
    at e.initialize (leaflet.browser.print.min.js:88:16)
    at new e (Class.js:24:20)
    at e.onAdd (leaflet.browser.print.min.js:679:32)
    at e.addTo (Control.js:70:42)
    at thirdfile.js:40:47

Hi Igor-Vladyka, I actually had similar problem pasted above.  I have also added this piece of code below to my code 

let browserControl = L.control.browserPrint().addTo(map);

Below is the pic of my code. Is there some part of the leaflet library that I am missing? what could that possibly be?

Br,
Simon


<img width="677" alt="Screenshot 2024-07-26 at 23 16 56" src="https://github.com/user-attachments/assets/8f735b15-923c-4ead-97ec-2c1c65d48f22">
