### ISSUE TITLE
How to add Custom Logo image and custom attribute text while printing

### ISSUE THREAD

**Issue by CityBelfast** [Igor-Vladyka/leaflet.browser.print#109]
Hi,
I'm using a custom logo image and custom attribute text on the map. But when I print this map using leaflet.browser.print library those details are missing.
![image](https://user-images.githubusercontent.com/76213912/147165886-8c74a1f9-736d-45f4-a199-6cad0dae51c4.png)

Actual Logo
![image](https://user-images.githubusercontent.com/76213912/147165969-73f709f4-fedf-41af-ac21-96171bdcbaea.png)

So, would you please give some idea about how to add custom image logo and custom attribute while printing map?

**see the below printing code**

  L.control.browserPrint({
                position: 'topright',
                closePopupsOnPrint: true,
                printModes: [
                    L.control.browserPrint.mode.landscape(),
                    L.control.browserPrint.mode.portrait()
                ],
                manualMode: false
            }).addTo(map);

             map.on(L.Control.BrowserPrint.Event.PrePrint, function (mode) {
                debugger;
                map.attributionControl.addAttribution('<a target="_blank" class="non-active">Copyright OS 2021</a>');
                $("div.leaflet-control-attribution a:not(:last)").remove();
                $("div.leaflet-control-attribution").contents().filter(function () { return this.nodeType === 3 }).remove();
            });

**Comment by Igor-Vladyka** [comment]
Hey there.

When printing we create basically a new map, so your logo is missing on it. You need to add it one more time for each print.
```
map.on("browser-print-start", function(e){
					/*Add same code for a logo here, and it will work*/
				});
				```

**Comment by CityBelfast** [comment]
Thanks
