### ISSUE TITLE
Printing polygons with custom fill patterns

### ISSUE THREAD

**Issue by rallep** [Igor-Vladyka/leaflet.browser.print#112]
Firstly, thank you for a great plugin - highly appreciated.
I am trying to print polygons where some of the polygons have a custom fill pattern created with https://github.com/teastman/Leaflet.pattern
When trying to print these the following warning is thrown: Unknown layer, cannot clone this layer. Leaflet version: 1.7.1, and the patterns are not printed. 
When investigating the printMap and printObjects in e.g., the browser-print-start event, the pattern seems to be present in the map object, but not in the polygon fillpattern option. Maybe caused by the issue that throws the warning.
I am unsure on how to proceed with trying to fix this. Would i need to registrer these patterns somehow before printing?

Thank you in advance for the help.

**Screenshots**
Screenshot of polygons, where one polygon has the pre-build stripes pattern from the aforementioned lib.
<img width="591" alt="image" src="https://user-images.githubusercontent.com/11444820/153938826-e6e12070-1ef7-4db6-a671-65d277927ee0.png">

Screenshot of browser-print-start event objects:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/11444820/153939286-343ea4c1-a5c9-4f33-bf5a-917286fb3ef9.png">

Screenshot of the printObjects polygon with the missing fillPattern:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/11444820/153939609-93abbd14-c0d8-4553-91df-dcbf7e1c1700.png">

**Comment by Igor-Vladyka** [comment]
Hey there. Please check solution in this isse #98 and let me know if you have more questions.

**Comment by rallep** [comment]
Great! Thank you - looks like that might be the solution I am looking for :-)

**Comment by Igor-Vladyka** [comment]
Please reopen the ticket if any.
