### ISSUE TITLE
Adding title to map

### ISSUE THREAD

**Issue by Mapjotr** [Igor-Vladyka/leaflet.browser.print#12]
Hi,
first of all thanks for the great tool. Works great!
I have one question though: Is there the opportunity to add a title or subtitle to the map? 
(I don't know if this is right place to ask of if there is something like a mailing list.)

Regards,
Peter

**Comment by Igor-Vladyka** [comment]
Hello,

There is a couple of ways to do it. Depends on your need. I can add an example with a Title/Subtitle if you explain/show some example of how do you see it.

Regards,
Igor

**Comment by Mapjotr** [comment]
I was thinking of something very easy like this:

![map_with_title_subtile](https://user-images.githubusercontent.com/14098495/32545457-16176336-c47c-11e7-855c-4a614edf3861.png)

It just would be great to have the opportunity to write a date, an author or an short annotation above or below the map.

**Comment by Igor-Vladyka** [comment]
I see,

I planned to add a possibility for custom content printing(Like title/subtitle) in next release (v0.4);
Currently, it's under development.

Regards,
Igor

**Comment by Mapjotr** [comment]
That sounds like a pretty useful feature! Looking forward to v0.4 :-)

**Comment by Igor-Vladyka** [comment]
Hey there,

I just released next version(v0.4) of a map with a possibility to specify any kind of content you want to print.
Here is an example that you can check to see how it works(it's just CSS+HTML and nothing more). You can specify content just for printing (hide print content before it's printed) or you can use an attribute to mark existing content that should be added and printed. [Demo](https://igor-vladyka.github.io/leaflet.browser.print/), [working code](https://github.com/Igor-Vladyka/leaflet.browser.print/blob/master/index.html)

Regards,
Igor
