### ISSUE TITLE
Text of Leaflet Geoman Textlayer is not displayed 

### ISSUE THREAD

**Issue by Lauranna** [Igor-Vladyka/leaflet.browser.print#121]
Hello Igor-Vladyka,

thanks for your great plugin.
I use the Leaflet Geoman-free plugin to give users the ability to insert graphics and text into the map themselves.
All graphics are displayed wonderfully on the print page.
Only the text in the text layer is not displayed. Here only an empty text field remains on the print page.

![leaflet geoman textlayer not working for print](https://user-images.githubusercontent.com/7869457/196426577-cf51d41a-73f2-4b89-9fde-a019e7d07e47.png)

But all I see is that:
![print page with textarea](https://user-images.githubusercontent.com/7869457/196427301-6fcf03e8-21b4-4290-b954-a9b787e7d234.png)

The text in the text box is missing.
Do I have to include anything else here? 

var browserPrint = L.control.browserPrint({
	title: 'Bild exportieren',
	documentTitle: '...',
	printModes: [
		L.BrowserPrint.Mode.Landscape("A4", {title: "Querformat"}),
		L.BrowserPrint.Mode.Portrait("A4", {title: "Hochformat"})
	],
	manualMode: false,
	closePopupsOnPrint: false,
	cancelWithEsc: false
}).addTo(map);

I'm sorry, I'm quite a beginner, but I hope you understand my problem.

Regards, 
Lauranna

**Comment by Falke-Design** [comment]
Hi @Lauranna,

you need to add following:
```
L.BrowserPrint.Utils.registerLayer(L.Marker, 'L.Marker', function(layer, utils) {
    var options = utils.cloneOptions(layer.options);
    if(layer.pm && layer.pm.getShape() === 'Text') {
        options.text = layer.pm.getText();
        delete options.icon;
    }
    return L.marker(layer.getLatLng(), options);
});
```

**Comment by Lauranna** [comment]
Thank you very much. 
It works.
