### ISSUE TITLE
[Geotiff] Geotiff file on print

### ISSUE THREAD

**Issue by mateuszbem** [Igor-Vladyka/leaflet.browser.print#127]
Have you ever tried priting *.tiff files (layerGroup)?

I'm using https://github.com/GeoTIFF/georaster-layer-for-leaflet for showing .tiff files on map, but when it comes to printing it doesn't show.
![image](https://github.com/Igor-Vladyka/leaflet.browser.print/assets/37087603/214ebc65-6f58-4d37-adf7-575c53b867fe)
and the effect:
![image](https://github.com/Igor-Vladyka/leaflet.browser.print/assets/37087603/7bb5e900-4bb8-4c47-8bfa-b8f4482d2bcf)

**Comment by mateuszbem** [comment]
`    this.layerGroup = L.layerGroup().addTo(this.map);
    this.browserPrint = L.control.browserPrint({
      title: 'Geotiff test',
    }).addTo(this.map);
    L.BrowserPrint.Utils.registerLayer(
      L.LayerGroup,
      'L.LayerGroup',
      function(layer, utils) {
        const cluster: LayerGroup = L.layerGroup(layer._group.options);
        cluster.addLayer(utils.cloneInnerLayers(layer._group));
        return cluster;
      });`

**Comment by Igor-Vladyka** [comment]
**L.LayerGroup** is already in the list, you need to register actual layer that is missing => **GeoRasterLayer**
try
```
L.BrowserPrint.Utils.registerLayer(
  GeoRasterLayer,
  'GeoRasterLayer',
  function(layer, utils) {
    const cluster: GeoRasterLayer = GeoRasterLayer(layer._group.options);
    cluster.addLayer(utils.cloneInnerLayers(layer._group));
    return cluster;
  });
```

or something like that, you would need to debug/check what exactly to pass inside function.

**Comment by mateuszbem** [comment]
Thank you Igor, its works.

>     L.BrowserPrint.Utils.registerLayer(
      GeoRasterLayer,
      'GeoRasterLayer',
      function(layer: any) {
        const options: GeoRasterLayerOptions = {
          georaster: layer.options.georaster,
          opacity: 0.6,
          resolution: 128,
        };
        const cluster: Layer = new GeoRasterLayer(options);
        return cluster;
      });

**Comment by Falke-Design** [comment]
Following worked for me:
```
L.BrowserPrint.Utils.registerLayer(
        GeoRasterLayer,
    'GeoRasterLayer',
    function(layer) {
            return new GeoRasterLayer(layer.options);
    });
```
