### ISSUE TITLE
Cannot click on the "Custom" print option

### ISSUE THREAD

**Issue by tger** [Igor-Vladyka/leaflet.browser.print#13]
Reproduces on: https://igor-vladyka.github.io/leaflet.browser.print/examples/v1.2.0.html

This is a regression.

**Comment by Igor-Vladyka** [comment]
Hi there,

Tested on Windows 10 latest: Chrome/Firefox/IE11/Edge - worked just great.

Please specify more exact information about your problem, environment, and everything else that can help localize an issue.

Regards,
Igor

**Comment by Mapjotr** [comment]
Tested on Ubunutu 14.04 latest: Chrome/Firefox. Works great for me too.

**Comment by tger** [comment]
Stacktrace:
```
Uncaught TypeError: Cannot read property 'rectangle' of undefined
    at e._endAutoPoligon (leaflet.browser.print.min.js:formatted:170)
    at e.fire (leaflet.js:5)
    at e._fireDOMEvent (leaflet.js:5)
    at e._handleDOMEvent (leaflet.js:5)
    at HTMLDivElement.r (leaflet.js:5)
```

**Comment by Igor-Vladyka** [comment]
What browser/environment are you on?

**Comment by tger** [comment]
Chrome latest on Windows 10

**Comment by Igor-Vladyka** [comment]
I've done some refactoring and It should help in your case.

Please check it one more time here(with a disabled browser cache): https://igor-vladyka.github.io/leaflet.browser.print/examples/v1.2.0.html - and if you are able to reproduce it -> copy/paste stacktrace one more time.

Regards,
Igor

**Comment by tger** [comment]
Sorry for not having a look at this. Since reporting this we have moved to
an in-house developed printing solution. But I just verified now at it
indeed seems to work now.

2017-11-24 14:37 GMT+01:00 Igor Vladyka <notifications@github.com>:
