### ISSUE TITLE
Sometimes map overlay display blank before going into print mode.

### ISSUE THREAD

**Issue by lqmnhakeem217** [Igor-Vladyka/leaflet.browser.print#134]
I have developed a printing tool that allows users to print a map with a polygon embedded within it, which can then be inserted into a frame along with additional details. While this project is widely used on a large scale, some users have reported issues where the map image does not appear within the frame when printing. I am investigating the cause of this problem for sometime but I do not know what cause it beside the cloning layer.

The map consist of:
- multiple TileLayers.wms
- L.geojson

Mind sharing some insight on this issue. thankyou
![expected result](https://github.com/Igor-Vladyka/leaflet.browser.print/assets/92044826/ac3944ba-f8fa-4a7c-b454-42a29dcb2ca3)

https://github.com/Igor-Vladyka/leaflet.browser.print/assets/92044826/f2fdf7f8-fdb5-4dbc-ae63-a0b6f5099974

**Comment by lqmnhakeem217** [comment]
based on my investigation, it might be the layer render slow, and unable to completely render all tile before it print. is there a way to forcefully render all tile until the tile are loaded the proceed to _completepPrinting function. i dont understand how the clone method works. Please assist 😅

**Comment by Igor-Vladyka** [comment]
Hey.

You need to debug it and see what is going on.
Try next: override: [_getLoadingLayers](https://github.com/Igor-Vladyka/leaflet.browser.print/blob/master/src/leaflet.browser.print.js#L598) function and try to debug it.

During printing there is a check on all internal layers and wait for them to load, could be that something is breaking in between or for the underlying layer.

**Comment by lqmnhakeem217** [comment]
Upon investigating, i realize the issue might be the cookies during print process 
![Screenshot 2024-06-07 112025](https://github.com/Igor-Vladyka/leaflet.browser.print/assets/92044826/e366b267-1bd4-4bef-8e2d-2fc90785c65c)
as shown in the image. Currently trying to find a way to  implement header attribute when printing. If you have any suggestion on how, can you share it here.
