### ISSUE TITLE
example with angular

### ISSUE THREAD

**Issue by GZDP2583** [Igor-Vladyka/leaflet.browser.print#15]
Hello,

I'm trying to integrate your plugin in an angular application but I've not succeeded...

My map looks like this in my html code :
``<div leaflet style="height: 450px;"
    [leafletLayers]="layers"
    [leafletLayersControl]="layersControl"
    [leafletFitBounds]="fitBounds">
  </div>

Do you have un example ?

Thanks in advance for your help.

**Comment by Igor-Vladyka** [comment]
Hi,

I have no idea how your angular app works. Looks like it's angulal 1.x code with a [leaflet] directive? You should add it as any other control you are adding. Just check the documentation, and that should work fine.

Otherwise - just find a way to access map object itself and add browserPrint control as written in documentation example here: https://github.com/Igor-Vladyka/leaflet.browser.print

Regards,
Igor

**Comment by GZDP2583** [comment]
I have an Angular 5 application and I try to use your javascript in a typescript file but I don't succeed in calling the function "addTo" and I don't have a map object...

**Comment by sgrillon14** [comment]
fixed with this [PR](https://github.com/Igor-Vladyka/leaflet.browser.print/pull/17)

**Comment by sgrillon14** [comment]
@Igor-Vladyka , please, can you post a message when the new verion 0.5.0 (or 0.4.3) is ready for use in production?

**Comment by Igor-Vladyka** [comment]
version 0.5 ready to use.

**Comment by sgrillon14** [comment]
You can close this issue. 0.5.0 valided in my Angular project, thank you.

**Comment by Igor-Vladyka** [comment]
Cool. Can I ask you to create a simple example with Angular 5? To share it with everyone else.

**Comment by sgrillon14** [comment]
demo ready in this [PR](https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins/pull/1). You can up vote.
After this exemple is [here](https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins)

**Comment by Igor-Vladyka** [comment]
Thanks.

**Comment by sgrillon14** [comment]
Angular tutoriel ready for use : https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins/tree/master/Leaflet.BrowserPrint

**Comment by myagappan** [comment]
Great to see the below printing option article on map from https://github.com/Igor-Vladyka.

leaflet.browser.print

I'm new and work now on the angular application. After proper install, when I try to import the leaflet.browser.print in my facility-list-map.component.ts file and integrate the code I get "ERROR in src/shared/components/facility-list-map/facility-list-map.component.ts(62,17): error TS2339: Property 'browserPrint' does not exist on type 'typeof control'"

Can you help me to rectify the issue as soon as possible please?

Thanks in advance.

**Comment by myagappan** [comment]
Great to see the below printing option article on map from https://github.com/Igor-Vladyka.

leaflet.browser.print

I'm NEW and work now on the angular application. After proper install, when I try to import the leaflet.browser.print in my facility-list-map.component.ts file and integrate the code I get "ERROR in src/shared/components/facility-list-map/facility-list-map.component.ts(62,17): error TS2339: Property 'browserPrint' does not exist on type 'typeof control'"

Can you help me to rectify the issue as soon as possible please?

Thanks in advance.

**Comment by sgrillon14** [comment]
see chapter 4 of https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins/tree/master/Leaflet.BrowserPrint
