### ISSUE TITLE
warning with new leaflet version

### ISSUE THREAD

**Issue by astomas** [Igor-Vladyka/leaflet.browser.print#20]
Hi,
I have the following warning in console with your plugin since Leaflet v.1.3.1: "L.browserPrint(options) is obsolete and will be removed shortly, please use L.control.browserPrint(options) instead."

**Comment by Igor-Vladyka** [comment]
Hi,

Message added intentionally to inform future changes to the plugin.
Please change plugin initialization code to make it work in future versions.
