### ISSUE TITLE
Zoom change when print landscape

### ISSUE THREAD

**Issue by mgageo** [Igor-Vladyka/leaflet.browser.print#21]
Hi,
When I print "landscape" on http://ao35.free.fr/rennesatlas/ipa.html#lon=-1.68499&lat=48.13936&zoom=18, the zoom change from 18 to 17.
It's the same in the custom mode.

**Comment by Igor-Vladyka** [comment]
Hi,

It's due to your map HTML object dimensions. The logic tries to fit a map view to Landscape page dimensions (height/width ~ 297/210 ~~ 1.41). So in your case when screen relation dimensions differ much it will try to fit visible area with lover zoom.

What is your expected behavior? Can you describe all your use cases? If so, adjustments could be made if it's really important for you to not change the zoom level.

Regards,
Igor

**Comment by mgageo** [comment]
Thanks for your response.

I expect then I draw a select in custom mode to have exactly the same thing.
When I do a selection between the 4 circles, I have parts of the circles.
The map is with EPSG:2154 projection and the select is not horizontal.
If the select is a narrow horizontal rectangle, the zoom change.

In the landscape mode, I prefer to have white margin.

http://ao35.free.fr/rennesatlas/ipa.html#lon=-1.72748&lat=48.13860&zoom=18

![image](https://user-images.githubusercontent.com/2681495/35844838-d75973ca-0b0f-11e8-8493-0a7fd54c0768.png)
 

![image](https://user-images.githubusercontent.com/2681495/35844739-42eff6be-0b0f-11e8-990a-b375871664af.png)

**Comment by Igor-Vladyka** [comment]
You can add margin via CSS:
Example:
`<style leaflet-browser-print-content>
	.grid-print-container { padding: 10px; }
</style>`

About custom selection, you will not be able to get exactly what you want. You are printing a map, so everything that is near your selection is important also. On the other hand, the plugin tries to zoom to fit your selection, so in the case when your selection is too small (with max-zoom taking into account) to fit on the page, it will use lover zoom level for printing - as I understood that's your case.

The projection itself doesn't matter. General logic is working as is. Everything else is configurable.

Please let me know if you have any other questions or comments.

Regards,
Igor
