### ISSUE TITLE
tooltip issue

### ISSUE THREAD

**Issue by askart** [Igor-Vladyka/leaflet.browser.print#24]
hi, there!
thanks for this lib, it helps a lot
After binding tooltips to polygons print can't proceed to the end, and there are no tooltips on polygons.

**Comment by Igor-Vladyka** [comment]
Hi there,

Could be some internal plugin issue. Can you show me an example of your binding (maybe jsbin or just js code to reproduce this issue)?

Meanwhile, I will take a look on my own.

Regards,
Igor

**Comment by Igor-Vladyka** [comment]
Looks like I found and fixed a problem. Please check latest 0.5.12 version of the plugin.

Regards
Igor

**Comment by askart** [comment]
Thanks,
this issue has been resolved,
but the problem is, that plugin does not react to toggling tooltips

initially we have something like this:
polygon.bindTooltip(polygon.label, {permanent: false, direction: "center", opacity: 1})
init this function after some button clicked:
polygon.openTooltip()
and print plugin can't see tooltips that are dynamic

if i set permanent to "true", then it will print tooltips

Firstly i'm adding print plugin, then add polygons and tooltips

I've even remove/add plugin after toggling tooltips, but these actions didn't help
