### ISSUE TITLE
Is there any option to add title to the printed content before print event fires?

### ISSUE THREAD

**Issue by askart** [Igor-Vladyka/leaflet.browser.print#25]
this is not issue,
Is there any option to add title to the printed content before print event fires?

i've just single idea is to add option, that will add event that will postpone print events till title had not been set

**Comment by Igor-Vladyka** [comment]
Hi there. You mean that you will need to load title from external resource
or you will have it before?

You can use title option of print plugin to setup title for print page or
you can use custom content title as it's in one of the examples.

Please specify full use cases for me to help you.

Regards
Igor

**Comment by askart** [comment]
Title is not constant, but dynamic.
Like in the example, but title will be written by human.

**Comment by askart** [comment]
And as well as I've understood your title do both things:
act as button tooltip and title,
but for me these are totally different things.

**Comment by askart** [comment]
If you can answer my question or give some advice, I appreciate this.

**Comment by Igor-Vladyka** [comment]
Sorry for a delay, I'm on vacation right now.

I plan to separate options to the page title and the button title.

On the other hand, I need to think about this, maybe will add an option to cancel printing on browser-pre-print event. And then you will need to start printing manually with user selected options. Will test it and write you an code example.

**Comment by Igor-Vladyka** [comment]
You can use next code (you will need plugin version 0.5.8+):
`var pageSize, pageBounds;
			map.on(L.Control.BrowserPrint.Event.PrePrint, function(e){
				map.printControl.cancel(returnTrueIfTitleIsAbsentAndFalseIfAllowPrinting());
				pageSize = e.pageSize;
				pageBounds = e.pageBounds;
			});` to preserve user print selection
and code:
`map.printControl.print(pageSize, pageBounds);`
where returnTrueIfTitleIsAbsentAndFalseIfAllowPrinting() - in your case some function to validate if allow printing or not.

Event L.Control.BrowserPrint.Event.PrePrint always will be fired before printing (even with manual printing).
