### ISSUE TITLE
Can't print layers included in custom panes

### ISSUE THREAD

**Issue by Jonibigoud** [Igor-Vladyka/leaflet.browser.print#26]
Hi,
first thank you for your great work on this plugin.
I m using leaflet and angular5.
I add geojson layers to a map with custom pane option like this:

`this.layerOne = L.geoJSON(this.levelOne, { pane: "firstPane", style: style, onEachFeature:onEachFeature});
this.layerOne.addTo(this.mapService.map)`

But i get an error:  

> TypeError: Cannot read property 'appendChild' of undefined

If i remove the "pane" option in each layer i get no error. Is the pane option supported on this plugin?

**Comment by shongololo** [comment]
I am running into a similar issue.

If I pass either a `pane` or `style` option to the `geoJson` layer, then I get the error per the original post.

**Comment by Igor-Vladyka** [comment]
Hi guys,

Known issue, that appears in different cases. Somehow, internally, leaflet does not expose appropriately panes and other layer stuff, so my plugin can't automatically create a valid copy of items inside.

Currently, it's top priority issue here, but I'm on vacation right now, so you will need to wait :)

Regards,
Igor

**Comment by Igor-Vladyka** [comment]
Hi guys,

Problem with printing custom panes should be fixed. I'm just not sure how to test your use cases, so please get layest plugin version 0.5.14 and test it and let me know if it works for you. If not - please proved a full example to reproduce, understand and fix the issue.

**Comment by Jonibigoud** [comment]
Hi, Thanks a lot, that works for me!
