### ISSUE TITLE
Create image

### ISSUE THREAD

**Issue by JePedrosa** [Igor-Vladyka/leaflet.browser.print#27]
Hello, I am using your plugin and I would like to know if there would be the possibility of instead of loading the map alone and calling the browser function to print that would create an image directly. Thank you

I'm using leaflet 1.3.1 and the search engines for firefox and chrome

**Comment by Igor-Vladyka** [comment]
Hi there,

Image creation is not planned. You can use https://github.com/rowanwins/leaflet-easyPrint plugin for image creation.

Regards.

**Comment by HANCCF** [comment]
hello, i am thinking about the same thing, the moust needed is to export a map with full map element, including map Legend,map Frame, map title, Compass, map scale , which can be variables , added to a baseLayer map .
