### ISSUE TITLE
printing all of the active tile layers

### ISSUE THREAD

**Issue by fatemi994** [Igor-Vladyka/leaflet.browser.print#28]
I have a map with one background layer and some wms layers. it prints only one of the tile layers(the last one that added to the map)... is there any way to get all of the tile layers when printing?
thanks

**Comment by Igor-Vladyka** [comment]
Hello,

You have one base tiles layer and a few images over the map that you want to print? Can you create an example (jsbin/codepen or any other) to show your use case and recreate issue?

Regards,
Igor

**Comment by Igor-Vladyka** [comment]
I've added some improvements, not sure if they will help. Please check the latest version and let me know if it works for you or not. And if not - please provide an example to reproduce and understand the issue.

**Comment by fatemi994** [comment]
thanks. I checked the latest version but still I have this problem... 
I created an example here: [https://jsfiddle.net/fatemi994/2s05gwxz/](url)

**Comment by Igor-Vladyka** [comment]
I see. Thanks. It should be fixed right now. Please check next version 0.5.13

Also, Auto printing will not work with WSM layers, will need to think about this problem later.
