### ISSUE TITLE
A3 printing

### ISSUE THREAD

**Issue by dominijk** [Igor-Vladyka/leaflet.browser.print#29]
How can i adjust to add A3 landscape print as an option, i thought i'd seen this on one of the demos but clicking again it's not there. When i use landscape or portrait it defaults to an A4 page size

**Comment by Igor-Vladyka** [comment]
Hello, currently you can't. This option is planned for the next release.

**Comment by dominijk** [comment]
Thanks for the great work

**Comment by Igor-Vladyka** [comment]
Hello, it's almost ready, currently it in a testing phase.
If you want to help, please get latest (it's not in npm for now, so you need latest github version(v0.6+) of the plugin). And use this syntax:

`L.control.browserPrint({
				printModes: [
					L.control.browserPrint.mode("Landscape", "Landscape BIG", "a3"),
					L.control.browserPrint.mode("Landscape", "Landscape normal", "a4"),
					L.control.browserPrint.mode("Portrait", "Portrait small", "a5"),
					L.control.browserPrint.mode("Auto", "Auto calculation", "B4"),
					L.control.browserPrint.mode("Custom", "Séléctionnez la zone USA", "B5")
				]
            }).addTo(map);`

Where: `L.control.browserPrint.mode(printMode, buttonText, pageSize)`;

Waiting for a comments.

P.S. Currently there is a couple of issues, but it should work with some 'manual user work', like changing pageSize in the print window manually if the browser will refuse to change automatically. :)

Regards,
Igor
