### ISSUE TITLE
Plugin crashes if leaflet routing machine is used.

### ISSUE THREAD

**Issue by sanastasiou** [Igor-Vladyka/leaflet.browser.print#3]
leaflet.browser.print.min.js:10 Uncaught TypeError: Cannot read property 'addTo' of undefined
    at NewClass._setupPrintMap (leaflet.browser.print.min.js:10)
    at NewClass._addPrintMapOverlay (leaflet.browser.print.min.js:10)
    at NewClass._print (leaflet.browser.print.min.js:10)
    at NewClass._printPortrait (leaflet.browser.print.min.js:10)
    at HTMLLIElement.handler (DomEvent.js:72)

To reproduce, simply include leaflet routing machine in any of your examples, and add a routing control to the map:

var routingControl = L.Routing.control({
                routeWhileDragging: false,
                showAlternatives: false,
                useZoomParameter: true,
                show: false,
                collapsible: true,
                lineOptions: {
                    addWaypoints: true
                },
                position: 'bottomright'
            }).addTo(map);

Plugin will crash, cause it cannot clone/use some layer that is added by the routing machine.

**Comment by Igor-Vladyka** [comment]
Added code to handle unknown layer. It will not be presented on the printed map, but will not fail.
