### ISSUE TITLE
Icons not loaded while printing.

### ISSUE THREAD

**Issue by habib-farhan** [Igor-Vladyka/leaflet.browser.print#32]
Hi, 
I have this small issue which i dont undertand. when i print the map the leafeltIcons are not show. I use another plugin leaflet.awesome-markers which has a base icon and another glyphicon or fontawesome icon on top.
the glyphicon and fontawesome icons are shown however the base icon which comes from the plugin are not.
here are images for a better understanding 
![printimage](https://user-images.githubusercontent.com/19238093/37964426-bada7b08-31c1-11e8-8474-e126e182d515.png)
![printimage2](https://user-images.githubusercontent.com/19238093/37964427-baf6189a-31c1-11e8-836c-e6ce72c357ef.png)

Any help is appreciated.
Thanks in advance.

**Comment by Igor-Vladyka** [comment]
Hello,

That's a bit strange. Please try to debug it. You can activate manualMode and debug the map itself.

`L.control.browserPrint({manualMode: true});`

Regards,
Igor
