### ISSUE TITLE
Graphic or legend  display problem

### ISSUE THREAD

**Issue by diouck** [Igor-Vladyka/leaflet.browser.print#33]
Hello
I just integrated the pluggin into an application. It works but I would like to know why I can not print a graphic. I test manual mode or the graph is displayed but when printing it is no longer there.
thank you for your understanding 
![mode_manuelle](https://user-images.githubusercontent.com/3952114/38425921-7f846194-39b5-11e8-85fd-5cd275b34f05.jpg)

![mode_auto](https://user-images.githubusercontent.com/3952114/38426033-c9751708-39b5-11e8-8f78-620c8dbf388a.jpg)

**Comment by Igor-Vladyka** [comment]
Hello,

Wow, that's weird. Can you create an example for me to debug it?

**Comment by diouck** [comment]
Hello
The application is part of a set but with this link you can see this legend that I want to add and that is not displayed

I changed from
....
  panels: {
            basic: function () {				//first panel
                $('.panelLegend').remove();
                var legend = L.control({position: 'topleft'});

                legend.onAdd = function (map) {
                    var e = carte.param;

                    var content = '<div class="panel panel-default" >'
                            + '<div class="panel-heading text-center text-uppercase dtable">'
                            + '<div class="dcell little-cell"><span class="fa fa-chevron-down hover-circle top-left-corner"></span></div>'
                            + '<div class="dcell" leaflet-browser-print-content><b>' + e.details.panel_titre + '</b></div>'
                            + '<div class="dcell little-cell" ></div>'
                            + '</div>'
                            + '<div class="panel-body">';

                    if (e.details.panel_lib) {
                        content += '<p id="strongtitle"><strong>' + e.details.panel_lib + '</strong></p>';
                    }

                    if (e.indics[2]) { //mult indics
                        content += carte.panels.options.all_indics(e.indics);
                    }

                    content += '<div class="colorsLegend pb10" **leaflet-browser-print-content** ><label>LÃ©gende :</label><div class="clearfix" >';
                    $.each(e.aplat.colors, function (i, v) {
                        content += '<i data-toggle="tooltip" data-placement="bottom" title="' + e.aplat.txt_classes[i] + '" '
                                + 'style="background : ' + e.aplat.colors[i] + '; width : ' + e.aplat.width + '%;"></i>';
                    });

......

http://carto.auran.org/public/js/main.map.js

**Comment by diouck** [comment]
Not display in  content += '<div class="colorsLegend pb10" leaflet-browser-print-content

**Comment by Igor-Vladyka** [comment]
Looks like there is some override somewhere.

Please find this CSS: 
`-webkit-print-color-adjust: exact!important;` and check why it's not working properly. You are using background-color property to specify colors for legend and Chrome ignores this property on printing in optimization purpose.

Regards,
Igor

**Comment by dimmu88** [comment]
NO render PNG :(
![1](https://user-images.githubusercontent.com/39884479/42127493-0d2cc980-7c57-11e8-8dd8-bf6bf741c835.png)
![2](https://user-images.githubusercontent.com/39884479/42127495-1b466bca-7c57-11e8-98a6-2d81b86edbae.png)

**Comment by Igor-Vladyka** [comment]
Hello,

This plugin not supposed to render PNG. Can you make an example to reproduce your rendering issue?

**Comment by dimmu88** [comment]
I am using the fontawesome marker plugin and I do not load the marker that is in png format, only that they are svg

**Comment by Igor-Vladyka** [comment]
So your problem is with fontawesome marker plugin. After quick googling I found out this issue: [Print marker background issue](https://github.com/lvoogdt/Leaflet.awesome-markers/issues/56) - please red it carefully and you will see how to fix your problem.

Please let me know if you have other problems with my plugin.
Kend regards,
Igor
