### ISSUE TITLE
Display is just blank

### ISSUE THREAD

**Issue by ramblerswebs** [Igor-Vladyka/leaflet.browser.print#34]
Hello
I have just added your extension to a leaflet map.
I added the js file and added the print control
When I hover over the print icon the four options appear.
Whichever of the four I click on the screen goes completely blank and then the printer dialogue appears.
I am using Leaflet 1.3.1
I get one error message that I do not understand
Unknown property 'size'.  Declaration dropped. index.php:1:333
as line one is doctype and line 133 is blank.

I am not sure how to debug this?

**Comment by Igor-Vladyka** [comment]
Hello,

Sorry for late reply. I hope you managed to solve your problem. Otherwise please create any working example of the problem and share it with me to be able to debug it manually.

Kind regards,
Igor

**Comment by ramblerswebs** [comment]
Igor
no worries, good of you to get back to me.
I have tried to debug it but cannot see what is wrong. I am fairly new to JS, so could be doing something stupid. Could be a conflict with other extensions I am using but I cannot see it.
I will set up a page for you that demonstrates the problem. Will take me two of three days to get to it.
Will get back to you then

**Comment by ramblerswebs** [comment]
Igor
I just realised I could get a test page up very easily.
If you go to 
https://www.ramblers-webs.org.uk/about-us/285-mapping-draw-your-own-route-track-2.html
you will see the Print icon on the left and leaflet.draw icons on the right.
Clicking on Print results in a blank page for printing

**Comment by Igor-Vladyka** [comment]
Hi there again.

I'm not sure how that happened, but looks like you are using an old version of the plugin. Please use latest from the NPM: https://www.npmjs.com/package/leaflet.browser.print or just download latest from te github itself.
