### ISSUE TITLE
Leaflet.markercluster: clusters partially brokens when printing

### ISSUE THREAD

**Issue by alexey-gl** [Igor-Vladyka/leaflet.browser.print#35]
Hello!
I have map with Leaflet.markercluster layer. When I trying to print it I have only text labels from clusters and all text labels from original makers (without clustering).
Is Leaflet.markercluster compatible with browser.print or here are some bugs exists?
Thank you for help!

**Comment by Igor-Vladyka** [comment]
Hello, it's haven't tested yet. Will check it out and will be back to you.

**Comment by Igor-Vladyka** [comment]
I've made a pre-release of new functionality together with some fixes that now should work with Leaflet.markercluster. Please take a look and let me know if any.
