### ISSUE TITLE
can't print Google and Bing basemaps

### ISSUE THREAD

**Issue by astomas** [Igor-Vladyka/leaflet.browser.print#39]
I use the mutant-google and the leaflet-bing plugins to display google and bing basemaps. When I  use browser-print, the Google basemap is not displayed and I have a "No value provided for variable {subdomain}" error for Bing. Other basemaps (cartoDB, OSM...) are printed fine.
When using the standard chrome print menu, all basemaps are correctly printed.

A sample code reproducing the case is provided (I've just hidden my API key values).
[bug print plugin.html.txt](https://github.com/Igor-Vladyka/leaflet.browser.print/files/2115483/bug.print.plugin.html.txt)

**Comment by Igor-Vladyka** [comment]
Hi there. 
Those plugins are not supported yet. I don't plan to add support for each individual plugin, instead there will be an a factory function to register all layers for printing. Will update you shortly.

**Comment by Igor-Vladyka** [comment]
Hello again,

Please refer to readme section [new-print-layers-registration](https://github.com/Igor-Vladyka/leaflet.browser.print#new-print-layers-registration) to check how you can register your google and bing layers and more information.

Shortly, you have to do something like next:
`L.Control.BrowserPrint.Utils.registerLayer(
	L.BingLayer,
	"L.BingLayer",
	function(layer) {
		return new L.BingLayer(layer._key, layer.options);
	}
);`

**Comment by astomas** [comment]
Thank you. Do I have to register all basemaps like this? the doc indicate "a list of pre-registered layers", my understanding is I don't have to register these kind of layers. At the moment I have to manually register all type of layer even L.TileLayer and have multiple warnings "leaflet.browser.print.utils.js:143 Unknown layer, cannot clone this layer" when printing.

**Comment by Igor-Vladyka** [comment]
Hello. And thank you. You are right. There was an issue with initial layers initialization. Now it should work as expected. Please take latest, v0.6.8 and let me know if any.

**Comment by astomas** [comment]
It works now perfect, Google and Bing plugins included. Thanks a lot.

**Comment by neerajlk** [comment]
@astomas , could you help me by sharing code to register bing and google mutant layers? Thanks
