### ISSUE TITLE
Print orientation on IE / Edge / Firefox

### ISSUE THREAD

**Issue by RemyRRB** [Igor-Vladyka/leaflet.browser.print#40]
Hello,

It is not possible to change page orientation on IE 11, Edge and Fifrefox.
For firefox : 
- The last page print orientation is saved and it is not automatically changed/forced by the plugin option.

For IE11 / Edge
- Orientation is always set to "Portrait"
- When I change orientation to landscape, some layers / controls are lost or broken (I lose color on countries).

This can be reproduced on the leaflet.browser.print demo : 
https://igor-vladyka.github.io/leaflet.browser.print/

Best regards,

**Comment by Igor-Vladyka** [comment]
Yeah, that is a problem.
Please take a look here: http://css-discuss.incutio.com/wiki/Print_Stylesheets#The_.40page_rule_and_forcing_Landscape_orientation

Basically, I can't do anything with it. If you need to print correct in IE/FF in landscape you can try different plugin that will behave differently (like downloading image first and then printing, not from the browser itself).

**Comment by rmarzocchi84** [comment]
using the following style I partially solve some problem related to text wrap (e.g. subcontent) 

Perhaps can be useful 

```
 <style type="text/css">
firefox-style {
	white-space: pre-wrap; /* css-3 */
	white-space: -moz-pre-wrap; /* Mozilla, since 1999 */
	white-space: -pre-wrap; /* Opera 4-6 */
	white-space: -o-pre-wrap; /* Opera 7 */
	word-wrap: break-word; /* Internet Explorer 5.5+ */
	width:100%;
}
</style>
```
