### ISSUE TITLE
IE 11 custom print issues

### ISSUE THREAD

**Issue by murdocha** [Igor-Vladyka/leaflet.browser.print#41]
I didn't notice any warning in the readme about this, so posting here.

Using the demo site here:
https://igor-vladyka.github.io/leaflet.browser.print/

in IE 11, the background map (stamen watercolor) and markers show up, but not the feature polygons, or popup "balloon" layer (only popup text shows). I'm attempting to print directly to a PDF with a "print to PDF" print driver. There is no "print preview", but I assume that is an artifact of IE versus Chrome capabilities. Also, the orange CSS background colors are lost, in the IE 11 print

pic from IE 11 PDF output:
![image](https://user-images.githubusercontent.com/7988400/43423443-74d4bf54-941a-11e8-9563-86e14d8de20e.png)

This workflow (print to PDF) does work with Chrome browser.
pic from Chrome PDF output:
![image](https://user-images.githubusercontent.com/7988400/43418827-31f45260-940d-11e8-9b9f-572c976d0b21.png)

Please let me know if there is another option to make this work in IE 11...

**Comment by murdocha** [comment]
This demo code _does_ appear to be using the 1.3.1 version of Leaflet from a CDN. 
I do see that there are documented issues with custom printing with Leaflet version 0.7.7 in IE versions, but perhaps this may be an undocumented issue with later Leaflet versions and IE 11 as well?

**Comment by Igor-Vladyka** [comment]
Hi there, you are right, there is a problem with IE11. I will take a look, but not promice anything. It's quite old and strange browser with tons of problem(but still less problematic as it was with IE6-7 :) )

**Comment by RemyRRB** [comment]
To print background image and color on IE 11 you must force the option : 

1. click on Tools icon (alt + x)
2. go to Print > Page setup
3. Check "Print Background Colors and Images"
