### ISSUE TITLE
css Eliminated when printing controls 

### ISSUE THREAD

**Issue by ghost** [Igor-Vladyka/leaflet.browser.print#43]
hello lgor!
when i print my map with a scale control ,it works well in (please copy it to browser url for visit)
 [hancc.xyz](url)
but when i deploy the plugin in my own project built with vue ,troubles came and i could find the key to solve it, could u give me a hand ? thanks!
the code below i used both in the two demo, set the BrowserPrint options [manualMode:true] and see what happens in printed page.
`L.control.browserPrint({//etc...
manualMode: true});
L.control.scale({position:'topleft'}).addTo(map);
`
the printing progress :
css(the white background) works in manualMode:true printing page: 
![in printing page](https://user-images.githubusercontent.com/40970773/43942262-d84614a6-9ca9-11e8-94b8-0a0828674e85.PNG)
when i push the 'print' button i shoud get the pdf like : 
![2776446059](https://user-images.githubusercontent.com/40970773/43942281-ea00f332-9ca9-11e8-8bc7-e32a46377845.png)
 in face it is like:
![2537971359](https://user-images.githubusercontent.com/40970773/43942275-e3f6b9a4-9ca9-11e8-87e0-6b384563c7de.png)
the css is removed , and the words (100KM and 50mi) in the scale control can be selected like other words in html. actually, all the css will be eliminated when i push [print] button..
thanks a lot!
han

**Comment by HANCCF** [comment]
i 've set the control scale css
```<style>
.leaflet-control.scale{
background:#66ccff;
}
</style>
```
the #66ccff works in manualMode, but have no effects when i click the [print] button .
could u tell me the way to hignlight my control or,the progress of adding child to overla ?
does
`L.legendControl({position: 'bottomright'}).addTo(e.printMap);`   with the css above take an effect?
grateful
han
