### ISSUE TITLE
Not giving id to button

### ISSUE THREAD

**Issue by jerome-lemaire** [Igor-Vladyka/leaflet.browser.print#44]
**Is your feature request related to a problem? Please describe.**
Hello. I use your plugin in a page witch contain several leaflet maps.
So I have multiple id `leaflet-browser-print` in my page !

**Describe the solution you'd like**
Could you avoid using id and use class instead ?

**Comment by Igor-Vladyka** [comment]
Hi Jerome,

Yeah, you are right. Please check latest version 0.7.
