### ISSUE TITLE
Leaflet rotate - print

### ISSUE THREAD

**Issue by kristiansvenssonwsp** [Igor-Vladyka/leaflet.browser.print#46]
I tried this branch (using a rotated leaflet map):
https://github.com/fnicollet/Leaflet/tree/rotate-master

Your plugin works but the print does not end up rotated. I tried to see if I could make that change myself but cant figure out where to change it. Any ideas?

**Comment by Igor-Vladyka** [comment]
Can you provide full example in JSbin or similar? I need to debug it to see what is going on.

**Comment by oarque** [comment]
Hi, 
Here's is an JSbin example:

https://jsbin.com/pudupuq/1/edit?html,output

**Comment by Igor-Vladyka** [comment]
Tried to hack it but without success. Looks like there is an internal problem in rotate functionality that prevents it from proper map manipulation - therefor from proper printing with a plugin.

Anyway, have no plans for rewriting/fixing rotate plugin, maybe some fix will be introduced by initial rotate developer.
