### ISSUE TITLE
v1.2.0 Example not showing print button

### ISSUE THREAD

**Issue by euangordon** [Igor-Vladyka/leaflet.browser.print#48]
https://igor-vladyka.github.io/leaflet.browser.print/examples/v1.2.0.html

I am trying to follow the example codes, but this one is not working.

No print icon is shown on the map.

Error in Chrome Console:
```
Uncaught TypeError: Cannot read property 'printModesNames' of undefined
    at Function.L.control.browserPrint (leaflet.browser.print.js:598)
    at v1.2.0.html:47
```

Solution, you can add a title and documentTitle
```
    ctlPrint = L.control.browserPrint({
        title: 'mapName',
        documentTitle: 'mapName'
    }).addTo(map);

**Comment by Igor-Vladyka** [comment]
Hi,

All example is updated. Thanks for pointing it out.
