### ISSUE TITLE
browser-print-start fires after L.browserPrintUtils.cloneLayer

### ISSUE THREAD

**Issue by gvarela1981** [Igor-Vladyka/leaflet.browser.print#5]
I have a demo page, https://gvarela1981.github.io/leaflet.browser.print/examples/v1.0.3.html
It has a filled red circle and a green circle. 
When I press the print button 'browser-print-start' fires and it should set the red circle's fill to 'false' but it does not.
Then I set a new event 'pre-print' into the <leaflet.browser.print.min.js> before calling to L.browserPrintUtils.cloneLayer.
The second demo page https://gvarela1981.github.io/leaflet.browser.print/examples/v1.0.3-pre-print-example.html shows the red circle's fill get transparent before the printing, and then returning to a red fill as the event browser-print-end is executed.

**Comment by Igor-Vladyka** [comment]
Hey there,

Please check the latest version(0.3.5) for updates that should help you.
Added "browser-pre-print" event right before layer cloning, for DOM manipulation with reference objects (as you did it in your example, but this way you need to revert changes on "browser-print-end").

Also added an additional argument for "browser-print-start", "browser-print" and "browser-print-end" with printObjects (object with key - leaflet type, value - cloned print objects array that you will see on printed layer). This way you will have all the cloned layers and will be able to modify them, and these modifications will last only for that print action(No need to revert changes for printObjects layers). 

Please check example [here](https://igor-vladyka.github.io/leaflet.browser.print/examples/manipulations_v1.0.3.html).

**Comment by SadafZohra** [comment]
@Igor-Vladyka  link is not working
