### ISSUE TITLE
Problems in printing tooltips and markercluster

### ISSUE THREAD

**Issue by curtis18** [Igor-Vladyka/leaflet.browser.print#50]
Hello,

Thanks for the library. It helps a lot to print the map for leaflet!
It is found that the tooltips and markerclusters are unable to be printed with styles. Is there documentation or demo for solving these issues? Thanks a lot.

It works now. I updated css and fixed the issues. Thank you.

**Comment by wagneralbjr** [comment]
can you explain how you fixed this? same problem here.

**Comment by curtis18** [comment]
It is required to update the CSS at @media print.
