### ISSUE TITLE
A0 size print doesn't fit into print screen.

### ISSUE THREAD

**Issue by sirajjunior** [Igor-Vladyka/leaflet.browser.print#51]
I am trying to print leaflet map with A0 size but map does'nt completely fit on print screen. Print screen discards half of map width. Same issue occurs in A1, A2, A3. Print after size A4 works perfect.

I have attached screen shots of issue and jsfiddle of my code.

One more thing I need to know. Is there any way to increase font size of header and discard URL in footer?

![map in browser](https://user-images.githubusercontent.com/29246194/49918380-c6f83300-fec4-11e8-8370-3ec482b279a4.PNG)

![map in print screen](https://user-images.githubusercontent.com/29246194/49918381-c790c980-fec4-11e8-9e9f-fc22f6cd1130.PNG)

Code Sample 

http://jsfiddle.net/sirajjunior/LnzN2/6288/

**Comment by Igor-Vladyka** [comment]
Hi There,

Please use "+ More settings" to configure proper printing and add/remove header/footer of page.

If you want custom header: [check this documentation](https://github.com/Igor-Vladyka/leaflet.browser.print#printing-additional-content-section).

If it not work for you - you can use: [this instructions to download as PNG](https://github.com/Igor-Vladyka/leaflet.browser.print#download-map-as-image)

**Comment by sirajjunior** [comment]
Hi,
 Thank you for response. I will check documentation for custom header. Any idea about A0 print size issue? why it splits map into multiple pages.

**Comment by Igor-Vladyka** [comment]
Your browser does not support A0 printing.

**Comment by Igor-Vladyka** [comment]
This is kinda expected behavior :)

What do you think, how it should work? In edge cases, like on really small zoom, etc?)
