### ISSUE TITLE
Leaflet.markercluster: issue printing white clusters in Firefox

### ISSUE THREAD

**Issue by ramblerswebs** [Igor-Vladyka/leaflet.browser.print#52]
When I use Leaflet.markercluster: any clusters display fine on the print preview page BUT when you actually get the print off the printer the clusters have lost their colour settings and the circles are just white.

To see this go to https://www.derbyramblers.org.uk/walk-details/map-of-walk-locations.html
Print the page either to paper or PDF
I would have expected the same attributes of the clusters to get printed, color, font etc
This happens if I am using Firefox 64. but works fine in Chrome.

PS thanks for great extension.

**Comment by Igor-Vladyka** [comment]
Hi there,

The problem is not with Firefox or plugin itself but rather with a combination of your plugins.
You can check [general example](https://igor-vladyka.github.io/leaflet.browser.print/) that works as expected.

Regards,
Igor

**Comment by ramblerswebs** [comment]
Why do you close issues so quickly?
The general example you say that demos the issues is using an old version of leaflet and dos not use Leaflet.markercluster so I cannot see how this is relevant.

Some clue as to what plugin you think is affecting the issue would be good

**Comment by ramblerswebs** [comment]
Sorry I see you are not using an version of leaflet, I read the page wrongly.

**Comment by Igor-Vladyka** [comment]
You can try to open each external css that is in your HTML and search for "media print" or just "print" word as check what is going on there. On the other hand, Chrome and Firefox has some different CSS applying rules, so maybe it's an issue in firefox and it will be fixed soon, just google it.
