### ISSUE TITLE
Loading until load service

### ISSUE THREAD

**Issue by vmagalhaes** [Igor-Vladyka/leaflet.browser.print#54]
Hi,
In my project, the service takes 4 seconds to get data and until I got a 200 response nothing happen. And when I have a response, the window.print is fired.

Have a way to display some loading or something like that?

Thanks.

**Comment by Igor-Vladyka** [comment]
Hi, you can find a bunch of events that is fired by the plugin in the documentation - just subscribe to any of them and use your own busy indicator.
