### ISSUE TITLE
Print map size follow screen size

### ISSUE THREAD

**Issue by habibr** [Igor-Vladyka/leaflet.browser.print#56]
I need to print the map not as defined A or B sizes. Rather, the print should follow the size of the displayed map in the client's screen. Is it possible to do so?

**Comment by Igor-Vladyka** [comment]
Hi there.

How do you think this should work? Do your client have any other page formats on his printer?

Regards,
Igor

**Comment by habibr** [comment]
No, sorry, I mean not printing on printer. I should rephrase my question: I need to save image of the map with sizes following the client's screen.

**Comment by Igor-Vladyka** [comment]
There is a way, but some adjustments needed. Please wait couple of days to be updated.
