### ISSUE TITLE
Multiple renderers causing duplicate elements on print overlay

### ISSUE THREAD

**Issue by sthurston-nuvolo** [Igor-Vladyka/leaflet.browser.print#57]
**Describe the bug**
When utilizing multiple map renderers such as SVG and Canvas, the print overlay shows duplicates for records tied to the non-default map renderer.  

**To Reproduce**
1. Create simple map with default options (uses default SVG renderer)
2. Create new canvas renderer with L.canvas();
3. Add object to map using the canvas renderer.
4. Click the print button using any mode
5. Duplicate copies of the canvas rendered object are shown in the print overlay and print preview

**Expected behavior**
There should only be one copy of each layer showing in the print overlay and print preview

**Example**
https://jsfiddle.net/shannonthurston_nuvolo/9hn73j84/

**Additional context**
I experimented with the code and found that when the layers are cloned for the print overlay the 'renderer' option isn't getting tied to the cloned renderer(L.SVG or L.Canvas), but instead is being left to the original renderer from the underlying map and that is what seems to be causing the issue of duplication.  I can make the problem go away partially by modifying the builder functions to set the renderer option to null, but ideally the cloned layers should link to the cloned renderer.

**Comment by Igor-Vladyka** [comment]
Added proper renderer registration.
Please check your fiddle example and let me know if any.

Regards,
Igor

**Comment by sthurston-nuvolo** [comment]
Hi Igor,

I appreciate the fast response to fix this.  While I've been incorporating this into a more complex build, I found that the problem still exists if the user prints once then prints a second time and zooms on the manualMode preview page.  The problem seems to be that the layers are getting registered every time the print command runs and that seems to change the base renderer again so there are duplicate layers generated each time the print button is pressed. 
If you use the same example I gave above, you can see it showing duplicates after printing once, then printing again and zooming out or in with your mouse.  The desired effect would be to allow the user to zoom in or out to resize the map on the manual mode preview without duplicates, if that would be possible.  Thank you!

**Comment by Igor-Vladyka** [comment]
Hi there.

Yes, you are right, I missed that case.

Added new version with a proper behavior.

Regards,
Igor
