### ISSUE TITLE
Error when auto is set as single print mode

### ISSUE THREAD

**Issue by DankoHR** [Igor-Vladyka/leaflet.browser.print#59]
I am trying to print map with image overlay in auto mode. But when adding auto mode as single print mode following error occures: 

> Cannot read property 'Mode' of undefined
    at e._getMode (leaflet.browser.print.js:135)
    at e._printAuto (leaflet.browser.print.js:155)
    at HTMLDivElement.r (leaflet.js:5)

When adding a second print mode (e.g. landscape) to printModes array everything works fine. Below my code: 

    <body>
        <div id="mapid"></div>
        <script>
            // map init
            var map = L.map('mapid', {
                crs: L.CRS.Simple, 
                minZoom: -5
            });
            
            // set image overlay and bounds
            var bounds = [[0,0], [6623, 9363]];
            map.fitBounds(bounds);
            L.imageOverlay('plan1.jpg', bounds).addTo(map);
                
            //init print
            L.control.browserPrint({
                printModes: [
                    L.control.browserPrint.mode.auto()
                ]
            }).addTo(map);           
        </script>
    </body>

**Comment by Igor-Vladyka** [comment]
Hello.

Thanks for pointing that out. Problem solved in latest update. v0.8.3.

Please let me know if you have any other problems.

Regards,
Igor

**Comment by DankoHR** [comment]
Hi Igor,

thank you very much for the fast fix and response.
With 0.8.3 everythig works fine.

Regards
Daniel
