### ISSUE TITLE
i.createPane is not a function

### ISSUE THREAD

**Issue by qvs5010** [Igor-Vladyka/leaflet.browser.print#60]
Hi 

I keep getting the following error when i try to use the control.

i.createPane is not a function.

**Comment by Igor-Vladyka** [comment]
Hi,

Can you provide more information? It's not clear about error and your use case.

**Comment by Korella** [comment]
I've faced with similar thing: `overlayMap.createPane is not a function`
Can't figure out how to avoid it.

**Comment by Igor-Vladyka** [comment]
Hi there.

Can you create JSbin with this problem to reproduce? 

Regards,
Igor

**Comment by Korella** [comment]
The browser debug leads me to [this line of code]( https://github.com/Igor-Vladyka/leaflet.browser.print/blob/master/src/leaflet.browser.print.js#L529)

**Comment by Igor-Vladyka** [comment]
That is clear, what leaflet version do you use? looks like you use old one.

**Comment by Korella** [comment]
0.7.7

**Comment by Igor-Vladyka** [comment]
Yeah, just update to newest version, if possible.

**Comment by Korella** [comment]
Thanks a lot, I'll try to.
Btw, README file says:

> Compatible with Leaflet v0.7.7 and v1+.

That's confused me.

**Comment by Igor-Vladyka** [comment]
Yeah, I forgot to update it after v0.4 it's not supportable anymore.
Just take latest.
