### ISSUE TITLE
Non A/B Paper Sizes

### ISSUE THREAD

**Issue by tuckergordon** [Igor-Vladyka/leaflet.browser.print#61]
I would be great to have more paper sizes beyond just `A` and `B`. For example, being able to specify U.S. sizes such as `letter`, `legal`, or `tabloid` would be very useful. More examples can be found [here](https://www.papersizes.org/us-paper-sizes.htm). 

I haven't fully thought through how this could be implemented, so it's possible I'm missing a large obstacle, but it seems pretty doable through modification of `leaflet.browser.print.sizes.js`. Maybe add more fields to `L.Control.BrowserPrint.Size` or adjust `L.Control.BrowserPrint.Mode.prototype.getPaperSize()` to check for cases that are not `A` or `B` and handle them separately.

**Comment by Igor-Vladyka** [comment]
Hi,

I will add a set of Metric sizes to the plugin soon.

Regards,
Igor

**Comment by Igor-Vladyka** [comment]
Hi,

Added more page size options. Please check README.
