### ISSUE TITLE
Remove Browser Header/Footer

### ISSUE THREAD

**Issue by tuckergordon** [Igor-Vladyka/leaflet.browser.print#62]
I would like to be able to print Leaflet without the default print options (e.g. header, footer). If I add styles from the top answers [here](https://stackoverflow.com/questions/1960939/disabling-browser-print-options-headers-footers-margins-from-page) or [here](https://stackoverflow.com/questions/8228088/remove-header-and-footer-from-window-print), then the header and footer disappear when I just print the page. However, when I print via leaflet.browser.print, they still appear. Is there a way to solve this?

**Comment by Igor-Vladyka** [comment]
Hi, Please provide and example so I can check what is wrong with it.
