### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by adacurro-usgs** [Igor-Vladyka/leaflet.browser.print#63]
Hello @Igor-Vladyka . I am trying to print my map into PNG format.  I'm not sure if it's a bug on domtoimage plugin or on this plugin but I noticed that it does not support printing on fullscreen mode. I'm using this plugin -> https://github.com/Leaflet/Leaflet.fullscreen. 

This the result I often get is like this 

![image](https://user-images.githubusercontent.com/23489861/55751269-45985380-5a13-11e9-8dc9-6c38a190a9c2.png)

Tried it on Chrome and Firefox (latest version for both browsers)  sometimes it's even exporting into .txt file if I include the documentTitle option

Appreciate the help!

**Comment by adacurro-usgs** [comment]
Here's the proof where it exports it to .txt file

![image](https://user-images.githubusercontent.com/23489861/55751777-82b11580-5a14-11e9-92a6-75b2de0c83b6.png)

**Comment by Igor-Vladyka** [comment]
Hi,

You don't need fullscreen plugin to export/print map. browser print plugin isolates map + needed content(in this case there will be no additional content), creates fullscreen overlay and then zoom map to fit needed size.

In this case, fullscreen plugin somehow overrides plugin behavior.

So, actually - you just need to specify correct map(paper/image) size to print plugin and it will do everything else.

Please let me know if you have any other questions, and/or problems, I'm ready to help.

Regards,
Igor
