### ISSUE TITLE
After dragging, map crash

### ISSUE THREAD

**Issue by Falke-Design** [Igor-Vladyka/leaflet.browser.print#64]
When the print map is loading the tiles it can be dragged. Please disable this.
But thats not the problem. After dragging the map, the print window is displayed, but then the map is white and all objects are gone.

**To Reproduce**
1. Click on the print button (no matter which type)
2. Drag the map
3. Cancle Print Window

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 66.0.5

**Comment by Igor-Vladyka** [comment]
Hi,

Thank you for reporting this. Plugin updated.

Regards,
Igor
