### ISSUE TITLE
Can't render layers of type L.gridLayer.geoJson

### ISSUE THREAD

**Issue by neerajlk** [Igor-Vladyka/leaflet.browser.print#65]
Hi, first of all a great work, getting map print to an ease, much appreciation.

Would request to add support for layer of type **L.gridLayer.geoJson** , since it isn't supported for print currently.
I'm a newbie at Leaflet,If it's simple or if I can do it externally then please do guide me for the same.

Thanks.

**Comment by Igor-Vladyka** [comment]
Hi,

It's easy. 
You code should look something like:
```js
L.Control.BrowserPrint.Utils.registerLayer(
	L.GridLayer.GeoJson,
	"L.GridLayer.GeoJson",
	function(layer, utils) {
		// We need to clone options to properly handle multiple renderers.
		return L.gridLayer.geoJson(/*layer.data (you need to put here geogson data)*/, utils.cloneOptions(layer.options));
	}
);
```
More information you can find in [README](https://github.com/Igor-Vladyka/leaflet.browser.print#new-print-layersrenderers-registration).

Regards,
Igor

**Comment by neerajlk** [comment]
Hi @Igor-Vladyka , Thanks for the quick reply. I tried your example and also referred to the guide but the layer doesn't get seen on the map preview. (neither any error is shown in console)

**Comment by Igor-Vladyka** [comment]
The idea here is to recreate layer. Your code looks good.
Please create an jsbin or so to reproduce it.
Also, I'm not familiar with this layer, where you took it? It's possible that whyle it's not oficially supported by leaflet - the logic behin it is a bit different and need other adjustments to make it work.

**Comment by neerajlk** [comment]
it uses **L.GridLayer.extend**  from here [Leaflet doc for GridLayer](https://leafletjs.com/reference-1.5.0.html#gridlayer)

**Comment by Igor-Vladyka** [comment]
Please provide an jsbin example to debug it.
