### ISSUE TITLE
custom print function

### ISSUE THREAD

**Issue by askart** [Igor-Vladyka/leaflet.browser.print#68]
I've noticed that custom print function had been changed, and now we need to pass mode inside print function? https://github.com/Igor-Vladyka/leaflet.browser.print/commit/f5646f48b4d18859ddde68adbc0d1736e5e2943f#diff-04c6e90faac2675aa89e2176d2eec7d8R76
`context[printFunc](mode)`

**Comment by Igor-Vladyka** [comment]
Yes, we need to provide print page information, so we need to pass fully functional module into it.

**Comment by Igor-Vladyka** [comment]
I just updated documentation with more information on custom print action, please take a look.
