### ISSUE TITLE
Add custom button for print function.

### ISSUE THREAD

**Issue by iamtekson** [Igor-Vladyka/leaflet.browser.print#69]
Since I want to add the custom button for print function, It doesn't work. My code is here;
` $('.print').click(function() {
    L.control.browserPrint.mode.landscape()
}); `
The Frontend button style for this plugin is not attractive and It shows the user only the limited option.
I want to print out the leaflet map when I click on print class from my HTML. If possible, I also want to add other functionality of this plugin in custom style in Frontend. Any help ?

**Comment by Igor-Vladyka** [comment]
Hi,

You need to call actual print plugin with a proper MODE.
In your code example, you are just creating default landscape MODE.

I just added new section into decumentation with needed information, please take a look:
[custom-print-button-action](https://github.com/Igor-Vladyka/leaflet.browser.print#custom-print-button-action)
