### ISSUE TITLE
Icon disappear when located plugin in the 'topright' or 'bottomright'.

### ISSUE THREAD

**Issue by iquays** [Igor-Vladyka/leaflet.browser.print#7]
Hi Igor,

Thanks for your simple yet useful plugin.
I can use your plugin with very easy steps. But when I located the plugin in 'topright' or 'bottomright', the printer icon is disappear when I hover the mouse over it.

Need your guidance please.
Thanks.

note: L.browserPrint({position: 'topright'}).addTo(map);

**Comment by Igor-Vladyka** [comment]
Hi there,

You are right, internal problems with styling. Now it should work as expected. Please check latest v0.3.7.

Regards,
Igor

**Comment by iquays** [comment]
Thanks for your super quick response.

Now it's worked perfectly.
