### ISSUE TITLE
Get event after custom select + change custom style 

### ISSUE THREAD

**Issue by luispina** [Igor-Vladyka/leaflet.browser.print#73]
Hi! First all, your plugin works so good! I started using the leaflet-easyprint of romanwins, but your plugin has fixed more things and for me is an essential plugin in all my leaflet projects.

However, there are a few things that i want to know if you could help to me:

- When the map has a big render (choropleth map with geojson with +150 MB size) and the user click in some option to print, there is a 'freeze time', before "browser-pre-print" event. The same thing after "browser-print-end", when the map comes back to his original zoom. In this case, it is very important give info to user than map 'is-doing-something-to-print' to avoid questions while processing. In proyects whose data viz is not too high this feature can be useless or not neccesary, but otherwise is essential.

To fix partially this, i added a jQuery 'blockUI' functionality to show some message while printing is loading to portrait, landscape and auto, but for 'custom' i can't catch just the event after select the rectangle and before "browser-pre-print" event (as i exposed above).

Do you know how can i get these two moments to show some status info?

(This issue is soft using Chrome but using Firefox the delay/freeze-time is too big so it is necessary give some info to user before and after save map image/PDF)

- Is there a way to change style options of custom print on the js code? When i select the custom mode, the L.rectangle has a similar color with my map background and it draw below all other tiles/panes. I want to change the colors (boundary and background's rectangle) and his z-index passing them as params if possible.

---

Here is a GIF to show the two points above, with Chrome [Version 76.0.3809.100 (Official Build) (64-bit)] and Firefox [68.0.2 (64-bit)], and a [minimal reproducible example](https://codesandbox.io/s/wizardly-sanderson-mmvn7vlqkp).

Example GIF in Chrome: 
![GIF Chrome](https://user-images.githubusercontent.com/7764817/63461067-d2253a80-c425-11e9-8e15-87ea3529821c.gif)

Example GIF in Firefox: 
![GIF Firefox](https://user-images.githubusercontent.com/7764817/63461109-f4b75380-c425-11e9-8e61-196b6c99862c.gif)

Thanks a lot!

**Comment by Igor-Vladyka** [comment]
Hi there.

I just added an option to style custom print rectangle with default pane zIndex = 9999. You can change the style or just update the color for it ;)

Also added new event as a first action when printing is initialized. This should help in your case.

Please let me know if any.

Regards,
Igor

**Comment by Igor-Vladyka** [comment]
Hi there.

Can you try to use events instead? It can be clearer and more maintainable. Example:

```
map.on(L.Control.BrowserPrint.Event.PrintInit, function(mode) {
$.blockUI({ message: '<h2><span><img src="'+require('./images/rolling202.gif')+'" /> Cargando impresión...</span></h2>' });
});
```

Regards,
Igor
