### ISSUE TITLE
Be able to download png as one of the options

### ISSUE THREAD

**Issue by gemmavnash** [Igor-Vladyka/leaflet.browser.print#74]
**Is your feature request related to a problem? Please describe.**
To be able to print the map as normal OR download a png.

**Describe the solution you'd like**
Instead of overriding the whole window.print like in https://igor-vladyka.github.io/leaflet.browser.print/examples/savePNG.html, I'd like the download png option to be one of the choices, not override all of them.

**Describe alternatives you've considered**

**Additional context**
I've tried the below, but I'm obviously off course.

```
var customActionToPrint = function (context, mode) {
    return function () {
      context._printAuto(mode);
      window.print = function () {
        domtoimage
          .toPng(document.body)
          .then(function (dataUrl) {
            var link = document.createElement('a');
            link.download = 'exportedMap.png';
            link.href = dataUrl;
            link.click();
          });
      }
    }
  }
  L.control.browserPrint({
    printModes: [
      L.control.browserPrint.mode("Download png", "Download png", "auto", customActionToPrint, false),
      L.control.browserPrint.mode.landscape(),
      L.control.browserPrint.mode.portrait(),
      L.control.browserPrint.mode.custom()
    ],
    position: 'topright'
  }).addTo(map);
```

**Comment by Igor-Vladyka** [comment]
Hi,

```
var customActionToPrint = function (context, mode) {
	return function () {
		var print = window.print;
		window.print = function () {
			return domtoimage
					.toPng(document.body)
					.then(function (dataUrl) {
						var link = document.createElement('a');
						link.download = 'exportedMap.png';
						link.href = dataUrl;
						link.click();
						window.print = print;
					});
		};

		context._printAuto(mode);
	}
}
```

Couple of points from exmple:
* You need to preserve original print function, replace it temporary and then restore.
* Actual print you should start after window.print override.
* You need to return promice with overrided print function to properly wait for PNG image composition.

Regards,
Igor

**Comment by gemmavnash** [comment]
Hi Igor
Many thanks for getting back to me.
Unfortunately this doesn’t work for me. it just gets stuck on the intermediate bit where everything but the map is removed (weirdly repositioning itself over Iceland) and then I get a load of errors about not being able to fetch resources.
Any ideas?
Thanks
Gemma

**Comment by Igor-Vladyka** [comment]
Hi,

It's dom-to-image issue.
https://github.com/tsayen/dom-to-image/issues/112

Regards,

**Comment by gemmavnash** [comment]
Sorry, I don't understand, but I'm guessing it's not going to work. Thanks for your help.
