### ISSUE TITLE
icon disappear when popup opened

### ISSUE THREAD

**Issue by astomas** [Igor-Vladyka/leaflet.browser.print#75]
I see the issue on my map and in the plugin example. 
When a popup is opened, the plugin won't be display and print the icon linked to the popup.

**Comment by astomas** [comment]
ok... 
I add a snap  of the plugin demo map: the icon disappear for printing when its popup is opened. Occurs on chrome, firefox.
![bugleafletprint](https://user-images.githubusercontent.com/4425097/64938613-d09d3580-d85e-11e9-8c20-6953deb02d2e.png)

**Comment by Igor-Vladyka** [comment]
Hi,

Yes, that is an issue. Will fix it in next version. Thanks

**Comment by Igor-Vladyka** [comment]
Hi there :) 

Now this problem if resolved for most scenarios.

Please let me know if any.

Regards,
Igor

**Comment by astomas** [comment]
thanks
