### ISSUE TITLE
HexBinLayer that Extends SVG

### ISSUE THREAD

**Issue by ssontag55** [Igor-Vladyka/leaflet.browser.print#76]
Any suggestion on this one?

@Igor-Vladyka happy to submit a PR or separate request if needed.  Thanks for the proj.

https://github.com/Asymmetrik/leaflet-d3/blob/master/src/js/hexbin/HexbinLayer.js#L20

```
L.Control.BrowserPrint.Utils.registerRenderer(L.HexbinLayer,"L.HexbinLayer",function(layer, options) {
      var hexLayer = L.hexbinLayer(layer.options);
      this.hexLayer.data(layer._data);
      return hexLayer;
    });

L.Control.BrowserPrint.Utils.registerLayer(L.HexbinLayer, "L.HexbinLayer",function(layer) {
      var hexLayer = L.hexbinLayer(layer.options);
      this.hexLayer.data(layer._data);
      return hexLayer;
    });
```

**Comment by Igor-Vladyka** [comment]
Hi, here 'HexBinLayer that Extends SVG' is basically a new renderer, so you have to only register renderer.
All layers will be rendered with hexbin renderer. Also, for renderer there is only one param inside builder function, that is options.
`L.Control.BrowserPrint.Utils.registerRenderer(L.HexbinLayer,"L.HexbinLayer")`

**Comment by ssontag55** [comment]
Thanks, works for downloading to image, but the print option doesn't register the layer since the data isn't sent to the Hexbin layer class.

**Comment by Igor-Vladyka** [comment]
Can you provide an full code example to see what's up with that? 
One of the options for now is to catch "L.Control.BrowserPrint.Event.PrintStart" event
`map.on(L.Control.BrowserPrint.Event.PrintStart, function(e){ ... });` and add data to renderer there.

**Comment by ssontag55** [comment]
There is data in the layer on `PrePrint` but it's removed on `Print`.  See data array:

![Screen Shot 2019-09-30 at 1 09 12 PM](https://user-images.githubusercontent.com/563334/65900570-47205400-e384-11e9-9949-163bc2e28dc5.png)

**Comment by Igor-Vladyka** [comment]
I'm not sure how it works internally, but you should use it only as a renderer, and not as both(renderer and layer). Therefore: try to remove registerLayer for HexbinLayer, and pass all needed data to it on PrintStart.

And any working example to debug it would be helpfull :)
