### ISSUE TITLE
Problems registering ESRI leaflet layers.

### ISSUE THREAD

**Issue by scaddenp** [Igor-Vladyka/leaflet.browser.print#78]
I am trying to get this to work ESRI leaflet layers. For instance, an imageMapLayer, (ultimately extends imageOverlay), I tried to register with:
                    L.Control.BrowserPrint.Utils.registerLayer(
                      L.esri.ImageMapLayer, "L.esri.ImageMapLayer", 
                            function(layer, utils) {
                                return L.esri.ImageMapLayer(layer.options);
                      }
                    );
(tried a few other variants too). Documented here - https://esri.github.io/esri-leaflet/api-reference/layers/image-map-layer.html
(other layer types also documented there).
When the browser runs, I get:
coreapp.js:139 TypeError: this.callInitHooks is not a function
    at Object.e [as ImageMapLayer]
    at Object.builder 
    at Object.cloneLayer
    at mainapp.js
    at Array.map (<anonymous>)
    at e._setupPrintMap 
    at e._addPrintMapOverlay 
    at e._print 
    at e.print 

layer.options seems to have all the correct values set at point when the builder calls it. Any pointers?

**Comment by Igor-Vladyka** [comment]
Hi,

Please check my answer [here](https://github.com/Igor-Vladyka/leaflet.browser.print/issues/77). Idea is the same.

**Comment by Igor-Vladyka** [comment]
#77
