### ISSUE TITLE
Cant register Vectorgrid layer

### ISSUE THREAD

**Issue by zogs** [Igor-Vladyka/leaflet.browser.print#79]
Hello,
First of all, thank you for this cool extension ! It's work like a charm.

Except it seems that Vectorgrid layer are not supported...
I tried to register it, but for some reason it is not working...

I made a sandbox so you can visualize what i tried -> [https://codesandbox.io/s/leaflet-vectorgrid-print-test-p0n0n](url). Maybe you can help me find what i did wrong...

Thank you

**Comment by Igor-Vladyka** [comment]
Hello, 

Here is updated codesandbox: [https://codesandbox.io/s/leaflet-vectorgrid-print-test-k9leh](https://codesandbox.io/s/leaflet-vectorgrid-print-test-k9leh).

You should use classes for registration and not factory methods.

Regards.
