### ISSUE TITLE
Popup options ignored

### ISSUE THREAD

**Issue by astomas** [Igor-Vladyka/leaflet.browser.print#8]
Hi,
when setting closePopupsOnPrint to false, the plugin prints the popup ignoring its options. 
For example in my code I set popup option to 'maxWidth:400' to display all my content inside the popup box but when printing with your plugin, the content stick out the popup box.
Standard print through browser menu is ok.
Thx

**Comment by Igor-Vladyka** [comment]
Hi there,

It's an issue. Right now it's fixed, please check latest 0.3.7 version.

Regards,
Igor
