### ISSUE TITLE
Map ends up on 2 pages. When windows dpi scaling is set to 150%

### ISSUE THREAD

**Issue by brunnernikolaj** [Igor-Vladyka/leaflet.browser.print#81]
When trying to print the map on windows with dpi scaling set to 150%, the map will overflow the first page and take up space on the second.

1. Go to windows display settings
2. Change scale / layout to 150%
3. try to print a map

Expected behavior
The map only takes up one page

**Screenshots**
![image](https://user-images.githubusercontent.com/7913222/69640570-db462900-105e-11ea-9bff-6595603b7277.png)

Desktop
 - Windows 10
 - Chrome
 - Version 78

**Comment by Igor-Vladyka** [comment]
Hi.

That is an interesting one. We cant control this behavior but I will take a look what can be done.

Regards,
Igor

**Comment by Igor-Vladyka** [comment]
Hi there,

I have adjusted calculations for printing. Please take a look and let me know if any.

Regards,
Igor

**Comment by promisethedeveloper** [comment]
Please what is the solution to this problem? As I am experiencing the same in my Angular application.
