### ISSUE TITLE
Print custom div instead of map div

### ISSUE THREAD

**Issue by rowheat02** [Igor-Vladyka/leaflet.browser.print#82]
I just want to print custom div(Main div in sketch), not only map div. Description div may contains any html element. Description div is not in L.control of the leaflet map.
![Drawing](https://user-images.githubusercontent.com/40065760/71708380-015aa800-2e19-11ea-82eb-b75cb90af35f.png)

**Comment by Igor-Vladyka** [comment]
Hi,

Please read details [here](https://github.com/Igor-Vladyka/leaflet.browser.print#printing-additional-content-section)

But basically you can do is:
```
<style leaflet-browser-print-content>
	.grid-print-container { // grid holder that holds all content (map and any other content)
		grid-template: 1fr / auto 10px auto;
	}
	.grid-map-print { // map container itself
		grid-column: 1;
	}
	.my-print-content {
		grid-column: 3;
		justify-self: center;		
		padding-left: 10px;
	}
</style>
<div class="my-print-content" leaflet-browser-print-content><<Map Description DIV>></div>
```
and put it somewhere into your body html.

Regards,
Igor

**Comment by Igor-Vladyka** [comment]
@rowheat02 Have you managed to achive what you where looking for?
