### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by mondeja** [Igor-Vladyka/leaflet.browser.print#88]
**Is your feature request related to a problem? Please describe.**
I would like to see what changes has been added to the library without check the commits.

**Describe the solution you'd like**
A CHANGELOG.md added that keeps tracks the changes made.

**Comment by Igor-Vladyka** [comment]
Hi there,

Yeah, plugin is growing, I may add one next time.

**Comment by Igor-Vladyka** [comment]
Added changelog.
