### ISSUE TITLE
Map in print not exactly bounded

### ISSUE THREAD

**Issue by johan14** [Igor-Vladyka/leaflet.browser.print#89]
**Bug**

Hi Igor,
When printing the map in a certain zoom, only a subset of the map is printed. I checked the bounds using pageBounds of browser-pre-print event, and they were okay. I used landscape mode. I've seen this issue occur also in the examples you've posted.

**Screenshots**

This is the map.

![image](https://user-images.githubusercontent.com/28931298/83153163-ec035480-a0fe-11ea-8855-d155cc0d4147.png)

This is the map in print.
![image](https://user-images.githubusercontent.com/28931298/83153279-11905e00-a0ff-11ea-9d63-e39b1bef15bf.png)

As you can see, the map in print crops pieces both left and right.

Please can you provide me with a solution?
Thank you,
Johan

**Comment by Igor-Vladyka** [comment]
Hello Johan,

So for Landscape mode: we are not invalidating bounds, so basically we are getting current map bounds by default, and then center map and print.
**Why:** As you can see the paper dimensions is different from your map(on screen) dimentions, so we cut sides.
**What to try:**
* For debugging to compare preview map on screen with browser preview please use [manualMode](https://github.com/Igor-Vladyka/leaflet.browser.print#usage)
* To invalidate bound and try to fit your map into page size, try creating not default landscape mode, example:
`printModes: [ L.control.browserPrint.mode(L.Control.BrowserPrint.Mode.Landscape, null, null, null, true)]`
more details [here](https://github.com/Igor-Vladyka/leaflet.browser.print#print-mode-details)

Please try it out and let me know if you need more help and/or information.

**Comment by johan14** [comment]
Hi Igor,
I tried your second suggestion, and it worked.
Thank you very much for your time!
