### ISSUE TITLE
Cluster marker not shown correctly

### ISSUE THREAD

**Issue by johan14** [Igor-Vladyka/leaflet.browser.print#90]
**The bug**

Hello Igor,
When printing a map with two markers not grouped into a marker cluster, it seems that both the markers and the cluster icon will be printed. The mode I've used is 
`L.control.browserPrint.mode(L.Control.BrowserPrint.Mode.Landscape, null, null, null, true)`

**Expected behavior**
When printing a map with markers not in a cluster, they should be printed separated. 

**Screenshots**
This is the state of map before printing.

![image](https://user-images.githubusercontent.com/28931298/84367265-478c1280-abd4-11ea-8a03-6ccac43c88e0.png)

This is the printed map.

![image](https://user-images.githubusercontent.com/28931298/84367402-7b673800-abd4-11ea-8d3a-4e0a411d6e05.png)

Maybe this happens because at printing, the map zooms out a little and the cluster icon is activated. 
Can you help me on how to display only the cluster icon, or only the markers, but not both?
Thank you,
Johan

**Comment by Igor-Vladyka** [comment]
Hi there.

Please try solution described here: [markerclustergroup](https://github.com/Igor-Vladyka/leaflet.browser.print#markerclustergroup-outofmemory-problem)

Regards,
Igor

**Comment by johan14** [comment]
Thanks Igor, it worked.
