### ISSUE TITLE
to many pages or wrong map

### ISSUE THREAD

**Issue by geoff21** [Igor-Vladyka/leaflet.browser.print#91]
hello.
if i use 
`leaflet.browser.print.js
leaflet.browser.print.sizes.js
leaflet.browser.print.utils.js`

or  `leaflet.browser.print.min.js`

i have the same problem.

in firefox, if i print a map i get 3 pages
the map i want with all the infos i add (title, legend ……) this one is perfect
the "original map" reprinting on screen
and a white page.

on chrome no problem at all

on edge i have the map overlaping the « original map »

when i try on your exemples no problems at all
only if i use  falkon as browser, it prints good size but « original map » 
p.s. i use falkon only for test cause it is supposed to be based on chrome.

leaflet.print 1.0.5

thank you

**Comment by Igor-Vladyka** [comment]
Hello,

Yes, there is a problems in other browsers that can ruin the experience, but taking into account that the majority users is using latest chrome based browser, there is no point for tuning it for each other browser (taking into account that they are changing somehing after each build and not consistent at all).

I tried to tune it for each browser at some point, but not now, it's just too much of a work

Regards,
Igor
