### ISSUE TITLE
Customize printed map content

### ISSUE THREAD

**Issue by LeandreLapidus** [Igor-Vladyka/leaflet.browser.print#92]
I'd like to thank you for the work you've done. I propose that it would be possible for the developer to define the content of the printout. Indeed some elements like the url are sometimes annoying.

So if for example it is possible to customize the content with a personal HTML code or at least define if its should be added (as it is done with the title of the document) i think it would be useful.

Sincerely,

**Comment by fishergisdldt** [comment]
i hava did it. i user borwser.print to generate a map then pass it to a image eidtor .in the editor you can add title and other map element. and move them.

**Comment by Igor-Vladyka** [comment]
Hello.

Right now you can specify content that you can use in addition to default browser printing (like margins, header and bottom link).
Please check it here [#printing-additional-content-section](https://github.com/Igor-Vladyka/leaflet.browser.print#printing-additional-content-section) and general example for more info.

Othervise, I'm not quite getting what do you want to so, so please put more details on expected result so I may suggest something.

Regards
