### ISSUE TITLE
when print type is auto ,some may have mistake

### ISSUE THREAD

**Issue by fishergisdldt** [Igor-Vladyka/leaflet.browser.print#93]
when map has no visiualLayers,print type is auto may cause mistake in file leaflet.browser.print.js line 350

if (!fitBounds) {
 fitBounds = this._map.getBounds();
}
return fitBounds;

change to:
if (!fitBounds ||fitBounds._southWest==undefined) {
  fitBounds = this._map.getBounds();
}
return fitBounds;

**Comment by Igor-Vladyka** [comment]
Hello. There should be no use cases when map has no visual layers :) But I will add check for it, thanks.

**Comment by Igor-Vladyka** [comment]
Added fix in latest version.
