### ISSUE TITLE
i have a new idea

### ISSUE THREAD

**Issue by fishergisdldt** [Igor-Vladyka/leaflet.browser.print#94]
when use this plugin ,I has no event to add title ,subtitle and images and so on. so I make a picuture editor,and  recive map from browsert.print. then pass it to the picture Editor.then you can move title to new placees ,and so on. then can make a professinal map.

**Comment by Igor-Vladyka** [comment]
Hello,

I'm not sure what do you mean, please describe in more specifics.

Right now you can setup a page layour with a css/html that will be used to construct print page.
[printing-additional-content-section](https://github.com/Igor-Vladyka/leaflet.browser.print#printing-additional-content-section)
