### ISSUE TITLE
Leaflet.browser.print + WMS

### ISSUE THREAD

**Issue by klaupher** [Igor-Vladyka/leaflet.browser.print#95]
Hi,

Unfortunately, I am not able to make your plugin work with my layers that are generated via WMS. Could you help me?
I followed the example below, since all the layers I insert I place in a layerGroup. In this way, I added, at the time of printing, these grouped layers, but even so they do not appear in the printout.

```
thisMap.on(L.Control.BrowserPrint.Event.PrintStart, function(e) {
	//L.legendControl({position: 'bottomright'}).addTo(e.printMap); origin code
        layerGroup.addTo(e.printMap); // my code
});

Do you have any ideia about this issue??
Regards,
Fernanda

**Comment by Igor-Vladyka** [comment]
Hello,

I'm not sure how to recreate an issue, can you please provide a demo anywhere (jsbin or anywhere else, or just send a code here) so it be easier to check it out?

Regards,
Igor

**Comment by klaupher** [comment]
Hello,

Sorry for delay in my answer. I was prepare your exemplo...
please, access: 

http://www.malujuartes.com.br/demoprint/
Thanks a lot.

**Comment by Igor-Vladyka** [comment]
Hello,

try removing this option, for demo, and let me know to check.

Looks like WMS layer right now attach itself to same base layer, and not to print layer. Therefore removing this option should work or will be easier to debug.

**Comment by klaupher** [comment]
Sorry, but what's option?? From L.tileLayer.wms?

**Comment by Igor-Vladyka** [comment]
![image](https://user-images.githubusercontent.com/5400062/91609581-ac3e4a00-e945-11ea-80c2-de4afe1d7e73.png)

**Comment by klaupher** [comment]
I removed the option that you suggested, but it didn't work anyway ...

**Comment by Igor-Vladyka** [comment]
Please also remove this part
```
    L.Control.BrowserPrint.Utils.registerLayer(L.TileLayer.WMS, 'L.TileLayer.WMS', function (layer) {
        console.info("Printing WMS layer.");
        return abrangenciaOverlay;
    });
```

**Comment by klaupher** [comment]
Hi, Igor!!
After remove the indicate part,, the print pluging works very well.... Now, I have a problem: why in my principal project it´s not work.. rsrsrs... Well.. Thanks for your huge help...

Regards,
Fernanda

**Comment by Igor-Vladyka** [comment]
Hello again,

It should be straight forward. SOmetimes we overcoplicate stuff when it's not need. Let me know if you need more help.

Regards,
Igor
